Algoritmo "teste entrada"

Var

idade : inteiro
salario1, salario2 : real
nome : caractere

Inicio

escreva ("Digite seu nome: ")
leia(nome)
escreva ("Digite sua idade: ")
leia(idade)
escreva("Digite quanto você ganhou nos dois últimos meses:")
leia(salario1)
leia(salario2)

escreval ("DADOS DIGITADOS")
escreval("Nome:",nome)
escreval("Idade:", idade)
escreval("Salario 1: ",salario1:8:2)
escreval("Salario 2: ", salario2:8:2)






Fimalgoritmo