Algoritmo "pares_consecutivos"


Var
n, soma : inteiro

Inicio
      escreva("Digite um número: ")
      leia(n)
      
      enquanto n <> 0 faca
               se n % 2 <> 0 entao
                  n <- n + 1
               fimse

               soma <- 5 * n + 20
               
               escreval("SOMA = ", soma)
               escreva("Digite um numero inteiro: ")
               leia(n)
      fimenquanto

Fimalgoritmo